### ISSUE TITLE
有一个bug

### ISSUE THREAD

**Issue by HighWarmModel** [hamger/hg-datepicker#1]
配置项属性end和默认时间设置一样的月份 默认时间不是属性initialOption设置的时间
`new DatePicker({
	inputId: 'start_date',
	type: 'date',
	start: [2017, 1, 1],
	end: [2018, 9, 17],
	initialOption: [2018, 9, 10],
	// end: [toyear - 0, tomonth - 0, today - 0],
	// initialOption: [beforeyear - 0, beforemonth - 0, beforeday - 0],
	success: function(arr) {
		start_date.value = arr.join('/')
	}
});
new DatePicker({
	inputId: 'end_date',
	type: 'date',
	start: [2017, 1, 1],
	end: [2018, 9, 17],
	initialOption: [2018, 9, 17],
	// end: [toyear - 0, tomonth - 0, today - 0],
	// initialOption: [toyear - 0, tomonth - 0, today - 0],
	success: function(arr) {
		end_date.value = arr.join('/')
	}
});`
![image](https://user-images.githubusercontent.com/21271880/45604864-38157f00-ba6b-11e8-93a9-b9eef967056d.png)
这里不需要减1吧

**Comment by hamger** [comment]
该 bug 在 v1.3.1 修复，由于配置相中的月份是从 1 开始的，`new Date()`中的月份是从 0 开始的，所以在这地方需要减一。
![image](https://user-images.githubusercontent.com/20814333/54899908-6b4e3480-4f0c-11e9-9d02-afb803829574.png)
