### ISSUE TITLE
当月份滑动时，日期变化值，点击确定不能正确获取值

### ISSUE THREAD

**Issue by glm1103** [hamger/hg-datepicker#4]
举例如下
开始的日期为  2018,3,31 日， 当仅滑动3月至4月时，当前focus日期将变百 2018,04,30 .  因"天“未触发touch或roll时，直接点击确定，获取的previousTime为 2018,4,31 日。

**Comment by hamger** [comment]
谢谢你提出的 issue ，该问题在 v1.3.2 中被修复
